version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_UNSIGNED_REQUESTS=true

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#      - QDRANT_HOST=qdrant
#      - QDRANT_PORT=6333
#      - GROQ_API_KEY=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
#    volumes:
#      - ./app:/app
#      - ./data:/app/data
#    depends_on:
#      - redis
#      - qdrant

volumes:
  redis_data:
  qdrant_data: